---@meta
---@diagnostic disable:unused-local

---@module 'spinner'
---@module 'job'

---@class Pipenv.CmdOpts: JobOpts

---Options for customizing your spinner.
---
---See https://github.com/xieyonn/spinner.nvim for more info about these options
--- ---
---@class PipenvSpinner.Opts
---@field attach? { text: string, status: PipenvOpts.SpinnerEventStatus }
---@field bufnr? integer
---@field col? integer
---@field fmt? fun(event: { text: string, status: PipenvOpts.SpinnerEventStatus }): string
---@field hl_group? string
---@field initial_delay_ms? integer
---@field kind? PipenvOpts.SpinnerKind
---@field ns? integer
---@field on_update_ui? fun(event: { text: string, status: PipenvOpts.SpinnerEventStatus })
---@field pattern? PipenvOpts.SpinnerPattern
---@field placeholder? boolean|string
---@field row? integer
---@field ttl_ms? integer
---@field ui_scope? string
---@field winblend? integer
---@field zindex? integer

---Options for customizing the `spinner.nvim` integration.
--- ---
---@class PipenvOpts.Spinner
---If `true` it will add a spinner while an operation is running.
---
---If `spinner.nvim` is not installed this will raise a warning and be ignored.
--- ---
---@field enabled? boolean
---Options for customizing your spinner.
---
---See https://github.com/xieyonn/spinner.nvim for more info about these options
--- ---
---@field opts? PipenvSpinner.Opts|spinner.Opts

---@class PipenvDefaults.Spinner: PipenvOpts.Spinner
---@field enabled boolean
---@field opts PipenvSpinner.Opts|spinner.Opts

---@class PipenvOpts.Output
---Can be a number between `0` and `1` (percentage) or a fixed width (only matters if `float` is `true`).
--- ---
---@field width? number
---Can be a number between `0` and `1` (percentage) or a fixed height (only matters if `float` is `true`).
--- ---
---@field height? number
---The `zindex` value of the output window (only matters if `float` is `true`).
--- ---
---@field zindex? integer
---Whether the output window should be a float or not.
--- ---
---@field float? boolean
---In what direction should the window be split (only matters if `float` is `false`).
--- ---
---@field split? 'right'|'left'|'above'|'below'
---The border type for the floating window (only matters if `float` is `true`).
--- ---
---@field border? 'none'|'single'|'double'|'rounded'|'solid'|'shadow'

---@class PipenvDefaults.Output: PipenvOpts.Output
---@field border 'none'|'single'|'double'|'rounded'|'solid'|'shadow'
---@field float boolean
---@field height number
---@field split 'right'|'left'|'above'|'below'
---@field width number
---@field zindex integer

---For more info see https://pipenv.pypa.io/en/latest/configuration.html#installation-and-dependencies
--- ---
---@class PipenvOpts.Env.InstallAndDeps
---If `false` then `$PIPENV_INSTALL_DEPENDENCIES` will be set to `0`.
--- ---
---@field install_dependencies? boolean
---If `false` then `$PIPENV_RESOLVE_VCS` will be set to `0`.
--- ---
---@field resolve_vcs? boolean
---If `true` then `$PIPENV_SKIP_LOCK` will be set to `1`.
--- ---
---@field skip_lock? boolean
---If non-nil then `$PIPENV_PYPI_MIRROR` will be set to its value.
--- ---
---@field pypi_mirror? string
---Will set `$PIPENV_MAX_DEPTH` to its value.
--- ---
---@field max_depth? integer
---Will set `$PIPENV_INSTALL_TIMEOUT` to its value.
--- ---
---@field install_timeout? integer
---Will set `$PIPENV_TIMEOUT` to its value.
--- ---
---@field timeout? integer

---@class PipenvDefaults.Env.InstallAndDeps: PipenvOpts.Env.InstallAndDeps
---@field install_dependencies boolean
---@field install_timeout integer
---@field max_depth integer
---@field pypi_mirror string
---@field resolve_vcs boolean
---@field skip_lock boolean
---@field timeout integer

---For more info see https://pipenv.pypa.io/en/latest/configuration.html#virtual-environment
--- ---
---@class PipenvOpts.Env.VirtualEnv
---If `true` then `$PIPENV_IGNORE_VIRTUALENVS` will be set to `1`.
--- ---
---@field ignore_virtual_envs? boolean
---If non-nil then `$PIPENV_PYTHON` will be set to its value.
--- ---
---@field python_path? string
---If non-nil then `$PIPENV_DEFAULT_PYTHON_VERSION` will be set to its value.
--- ---
---@field python_version? string
---If `true` then `$PIPENV_VENV_IN_PROJECT` will be set to `1`.
--- ---
---@field venv_in_project? boolean
---If non-nil then `$PIPENV_CUSTOM_VENV_NAME` will be set to its value.
--- ---
---@field venv_name? string
---If non-nil then `$PIPENV_VIRTUALENV` will be set to its value.
--- ---
---@field venv_path? string

---@class PipenvDefaults.Env.VirtualEnv: PipenvOpts.Env.VirtualEnv
---@field ignore_virtual_envs boolean
---@field python_path string
---@field python_version string
---@field venv_in_project boolean
---@field venv_name string
---@field venv_path string

---For more info see https://pipenv.pypa.io/en/latest/configuration.html#security
--- ---
---@class PipenvOpts.Env.Security
---If non-nil then `$PIPENV_PYUP_Core_KEY` will be set to its value.
--- ---
---@field pyup_api_key? string

---@class PipenvDefaults.Env.Security: PipenvOpts.Env.Security
---@field pyup_api_key string

---For more info see https://pipenv.pypa.io/en/latest/configuration.html#file-locations
--- ---
---@class PipenvOpts.Env.Behavior
---If `true` then `$PIPENV_DONT_LOAD_ENV` will be set to `1`.
--- ---
---@field no_load_env? boolean
---If `true` then `$PIPENV_DONT_USE_PYENV` will be set to `1`.
--- ---
---@field no_pyenv? boolean
---If `true` then `$PIPENV_DONT_USE_ASDF` will be set to `1`.
--- ---
---@field no_asdf? boolean
---If `true` then `$PIPENV_SHELL_FANCY` will be set to `1`.
--- ---
---@field fancy_shell? boolean
---If `true` then `$PIPENV_NOSPIN` will be set to `1`.
--- ---
---@field no_spin? boolean
---If `true` then `$PIPENV_QUIET` will be set to `1`.
--- ---
---@field quiet? boolean
---If `true` then `$PIPENV_VERBOSE` will be set to `1`.
--- ---
---@field verbose? boolean
---If `true` then `$PIPENV_YES` will be set to `1`.
--- ---
---@field auto_accept? boolean
---If `true` then `$PIPENV_IGNORE_PIPFILE` will be set to `1`.
--- ---
---@field ignore_pipfile? boolean
---Will set `$PIPENV_REQUESTS_TIMEOUT` to its value.
--- ---
---@field timeout? integer
---If `true` then `$PIPENV_CLEAR` will be set to `1`.
--- ---
---@field clear_cache? boolean
---If `true` then `$PIPENV_SITE_PACKAGES` will be set to `1`.
--- ---
---@field site_packages? boolean

---@class PipenvDefaults.Env.Behavior: PipenvOpts.Env.Behavior
---@field auto_accept boolean
---@field clear_cache boolean
---@field fancy_shell boolean
---@field ignore_pipfile boolean
---@field no_asdf boolean
---@field no_load_env boolean
---@field no_pyenv boolean
---@field no_spin boolean
---@field quiet boolean
---@field site_packages boolean
---@field timeout integer
---@field verbose boolean

---For more info see https://pipenv.pypa.io/en/latest/configuration.html#file-locations
--- ---
---@class PipenvOpts.Env.FileLocations
---If non-nil then `$PIPENV_CACHE_DIR` will be set to its value.
--- ---
---@field cache_dir? string
---If non-nil then `$PIPENV_PIPFILE` will be set to its value.
--- ---
---@field pipfile_path? string
---If non-nil then `$PIPENV_DOTENV_LOCATION` will be set to its value.
--- ---
---@field dotenv_location? string

---@class PipenvDefaults.Env.FileLocations: PipenvOpts.Env.FileLocations
---@field cache_dir string
---@field dotenv_location string
---@field pipfile_path string

---@class PipenvOpts.Env
---@field behavior? PipenvOpts.Env.Behavior
---@field file_location? PipenvOpts.Env.FileLocations
---@field install? PipenvOpts.Env.InstallAndDeps
---@field security? PipenvOpts.Env.Security
---@field virtual_env? PipenvOpts.Env.VirtualEnv

---@class PipenvDefaults.Env: PipenvOpts.Env
---@field behavior PipenvDefaults.Env.Behavior|nil
---@field file_location PipenvDefaults.Env.FileLocations|nil
---@field install PipenvDefaults.Env.InstallAndDeps|nil
---@field security PipenvDefaults.Env.Security|nil
---@field virtual_env PipenvDefaults.Env.VirtualEnv|nil

---@class Pipenv.CommandOpts
---@field python? string
---@field verbose? boolean

---@class Pipenv.RequirementsOpts
---@field dev? boolean
---@field file? string[]|string
---@field python? string
---@field verbose? boolean

---@class Pipenv.RemoveOpts
---@field verbose? boolean

---@class Pipenv.GraphOpts
---@field python? string

---@class Pipenv.SyncOpts: Pipenv.CommandOpts
---@field dev? boolean
---@field pre? boolean

---@class Pipenv.UpgradeOpts: Pipenv.SyncOpts
---@class Pipenv.UpdateOpts: Pipenv.SyncOpts
---@class Pipenv.CleanOpts: Pipenv.CommandOpts
---@class Pipenv.InstallOpts: Pipenv.SyncOpts
---@class Pipenv.LockOpts: Pipenv.SyncOpts
---@class Pipenv.RunOpts: Pipenv.CommandOpts
---@class Pipenv.ScriptsOpts: Pipenv.GraphOpts
---@class Pipenv.UninstallOpts: Pipenv.SyncOpts
---@class Pipenv.VerifyOpts: Pipenv.CommandOpts

---@class PipenvJsonPackage
---@field installed_version string
---@field key string
---@field package_name string

---@alias PipenvJsonGraph table<'package', PipenvJsonPackage>

---@class PipenvOpts
---@field env? PipenvOpts.Env
---@field output? PipenvOpts.Output
---Options for customizing the `spinner.nvim` integration.
--- ---
---@field spinner? PipenvOpts.Spinner

---@class PipenvDefaults: PipenvOpts
---@field env PipenvDefaults.Env
---@field output PipenvDefaults.Output
---@field spinner PipenvDefaults.Spinner

---@class PipenvEnvType
---@field type 'string'|'boolean'|'number'
---@field var string

---@class PipenvEnvTypes
---@field behavior table<string, PipenvEnvType>
---@field file_location table<string, PipenvEnvType>
---@field install table<string, PipenvEnvType>
---@field security table<string, PipenvEnvType>
---@field virtual_env table<string, PipenvEnvType>

---@alias PipenvOpts.SpinnerPattern
---|'aesthetic'
---|'arc'
---|'arrow'
---|'arrow3'
---|'balloon'
---|'balloon2'
---|'betaWave'
---|'binary'
---|'bounce'
---|'bouncingBall'
---|'bouncingBar'
---|'boxBounce'
---|'boxBounce2'
---|'circle'
---|'circleHalves'
---|'circleQuarters'
---|'dots'
---|'dots10'
---|'dots11'
---|'dots12'
---|'dots13'
---|'dots14'
---|'dots2'
---|'dots3'
---|'dots4'
---|'dots5'
---|'dots6'
---|'dots7'
---|'dots8'
---|'dots8Bit'
---|'dots9'
---|'dotsCircle'
---|'dqpb'
---|'dwarfFortress'
---|'fish'
---|'flip'
---|'grenade'
---|'growHorizontal'
---|'growVertical'
---|'hamburger'
---|'layer'
---|'line'
---|'line2'
---|'material'
---|'noise'
---|'pipe'
---|'point'
---|'pong'
---|'rollingLine'
---|'sand'
---|'shark'
---|'simpleDots'
---|'simpleDotsScrolling'
---|'squareCorners'
---|'squish'
---|'star'
---|'star2'
---|'toggle'
---|'toggle10'
---|'toggle11'
---|'toggle12'
---|'toggle13'
---|'toggle2'
---|'toggle3'
---|'toggle4'
---|'toggle5'
---|'toggle6'
---|'toggle7'
---|'toggle8'
---|'toggle9'
---|'triangle'

---@alias PipenvOpts.SpinnerEventStatus 'delayed'|'paused'|'running'|'stopped'

---@alias PipenvOpts.SpinnerKind
---|'cmdline'
---|'cursor'
---|'extmark'
---|'statusline'
---|'tabline'
---|'winbar'
---|'window-footer'
---|'window-title'

---@alias PipenvWinBorders
---|'bold'
---|'double'
---|'none'
---|'rounded'
---|'shadow'
---|'single'
---|'solid'

---@alias Pipenv.ValidOps
---|'clean'
---|'edit'
---|'graph'
---|'help'
---|'install'
---|'list-installed'
---|'list-scripts'
---|'lock'
---|'remove'
---|'requirements'
---|'run'
---|'scripts'
---|'sync'
---|'uninstall'
---|'update'
---|'upgrade'
---|'verify'

-- vim: set ts=2 sts=2 sw=2 et ai si sta:
